.catalog:
  name: "Owncloud"
  version: "v0.1-educaas"
  description: "Library service powered by Owncloud"
  uuid: owncloud-0
  minimum_rancher_version: v0.51.0
  questions:

owncloud:
  scale: 1
  health_check:
    port: 80
    request_line: GET / HTTP/1.0
    interval: 2000
    initializing_timeout: 60000
    reinitializing_timeout: 60000
    unhealthy_threshold: 3
    strategy: recreate

